window.CardCortexData = {
  cards: [
    {
      id: "pk-charizard-4",
      name: "Charizard",
      category: "Pokemon",
      set: "Base Set",
      number: "4/102",
      rarity: "Holo Rare",
      storage: "Binder A · page 1",
      rawValue: 438,
      gradedValue: 1240,
      grade: 9.1,
      confidence: 88,
      sources: { eBay: 452, TCGPlayer: 421, PriceCharting: 441, Cardmarket: 398 },
      color: "#ff7a45",
    },
    {
      id: "mtg-lotus",
      name: "Jeweled Lotus",
      category: "Magic",
      set: "Commander Legends",
      number: "319",
      rarity: "Mythic",
      storage: "Deck vault · commander",
      rawValue: 72,
      gradedValue: 168,
      grade: 8.7,
      confidence: 81,
      sources: { eBay: 69, TCGPlayer: 74, PriceCharting: 71, Cardmarket: 64 },
      color: "#7c5cff",
    },
    {
      id: "marvel-spidey",
      name: "Spider-Man Hologram",
      category: "Spider-Man",
      set: "Marvel Universe",
      number: "MH1",
      rarity: "Chase",
      storage: "Toploader box · row 2",
      rawValue: 126,
      gradedValue: 312,
      grade: 8.9,
      confidence: 84,
      sources: { eBay: 132, TCGPlayer: 0, PriceCharting: 119, Cardmarket: 0 },
      color: "#ed254e",
    },
    {
      id: "dbz-goku",
      name: "Son Goku, Awakened Power",
      category: "Dragon Ball Z",
      set: "Tournament of Power",
      number: "BT1",
      rarity: "Secret Rare",
      storage: "Slab case · shelf 1",
      rawValue: 690,
      gradedValue: 1850,
      grade: 9.4,
      confidence: 91,
      sources: { eBay: 710, TCGPlayer: 668, PriceCharting: 690, Cardmarket: 622 },
      color: "#f5b335",
    },
    {
      id: "bakugan-dragonoid",
      name: "Dragonoid Evo",
      category: "Bakugan",
      set: "Battle Brawlers",
      number: "D-88",
      rarity: "Super Rare",
      storage: "Binder C · page 4",
      rawValue: 34,
      gradedValue: 82,
      grade: 8.2,
      confidence: 76,
      sources: { eBay: 31, TCGPlayer: 0, PriceCharting: 37, Cardmarket: 0 },
      color: "#14b8a6",
    },
    {
      id: "minecraft-creeper",
      name: "Charged Creeper",
      category: "Minecraft",
      set: "Collector Series",
      number: "C-12",
      rarity: "Foil",
      storage: "Kids collection · green box",
      rawValue: 18,
      gradedValue: 44,
      grade: 8.5,
      confidence: 79,
      sources: { eBay: 16, TCGPlayer: 0, PriceCharting: 20, Cardmarket: 0 },
      color: "#44c553",
    },
    {
      id: "buddyfight-jackknife",
      name: "Jackknife Dragon",
      category: "Buddyfight",
      set: "Dragon Chief",
      number: "D-BT01",
      rarity: "RRR",
      storage: "Binder B · page 6",
      rawValue: 29,
      gradedValue: 73,
      grade: 8.6,
      confidence: 78,
      sources: { eBay: 27, TCGPlayer: 31, PriceCharting: 29, Cardmarket: 0 },
      color: "#2f80ed",
    },
    {
      id: "sports-jordan",
      name: "Michael Jordan All-Star",
      category: "Sports",
      set: "Upper Deck",
      number: "23",
      rarity: "Insert",
      storage: "Slab case · shelf 2",
      rawValue: 205,
      gradedValue: 610,
      grade: 9.0,
      confidence: 86,
      sources: { eBay: 218, TCGPlayer: 0, PriceCharting: 198, Cardmarket: 0 },
      color: "#111827",
    },
  ],
  marketplaces: [
    { name: "eBay", bestFor: "wide demand, auctions, graded and raw cards", fee: "variable", confidence: 96 },
    { name: "TCGPlayer", bestFor: "Pokemon, Magic, Yu-Gi-Oh, sealed product", fee: "marketplace", confidence: 93 },
    { name: "Cardmarket", bestFor: "European TCG demand and set-specific buyers", fee: "marketplace", confidence: 86 },
    { name: "COMC-style consignment", bestFor: "sports cards, portfolio sales, hands-off fulfillment", fee: "consignment", confidence: 82 },
    { name: "Local card shops", bestFor: "fast liquidity and bulk exits", fee: "spread", confidence: 74 },
    { name: "Collector communities", bestFor: "niche Marvel, Bakugan, Buddyfight, Minecraft cards", fee: "relationship", confidence: 78 },
  ],
};
